const nodemailer = require('nodemailer');

const sendEmail = async ({
  name,
  email,
  phone,
  department,
  doctor,
  subject,
  message,
  dateAndTimeBooked
}) => {
  // Create your transporter
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.MAIL_USER,     // your Gmail
      pass: process.env.MAIL_PASSWORD  // App Password
    }
  });

  const formattedDate = new Date(dateAndTimeBooked).toLocaleString();

  const mailOptions = {
  from: `"Hilton Multispecialist Hospital & Fertility Centre" <${process.env.MAIL_USER}>`,
  to: process.env.MAIL_RECEIVER, // e.g., hospital admin inbox
  subject: `🩺 New Appointment Request — ${subject}`,

  text: `
  New Appointment Request

  Name: ${name}
  Email: ${email}
  Phone: ${phone || 'N/A'}
  Department: ${department || 'N/A'}
  Doctor: ${doctor || 'N/A'}
  Subject: ${subject}
  Message: ${message}
  Preferred Date & Time: ${formattedDate}

  This appointment was submitted through the Hilton Hospital online booking system.
    `,

    html: `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; background-color: #f6f8fa; border-radius: 12px; max-width: 600px; margin: auto; border: 1px solid #ddd;">
      <h2 style="color: #1565c0; text-align: center;">🩺 New Appointment Request</h2>
      <p style="font-size: 15px; color: #444; text-align: center;">
        A new appointment request has been submitted via the Hilton Multispecialist Hospital online booking form.
      </p>

      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Full Name:</td>
          <td style="padding: 10px;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Email:</td>
          <td style="padding: 10px;">${email}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Phone:</td>
          <td style="padding: 10px;">${phone || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Department:</td>
          <td style="padding: 10px;">${department || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Doctor:</td>
          <td style="padding: 10px;">${doctor || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Subject:</td>
          <td style="padding: 10px;">${subject}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Message:</td>
          <td style="padding: 10px; white-space: pre-line;">${message}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; color: #333;">Preferred Date & Time:</td>
          <td style="padding: 10px;">${formattedDate}</td>
        </tr>
      </table>

      <div style="margin-top: 25px; font-size: 13px; color: #555; text-align: center;">
        <p>This email was automatically generated by the <strong>Hilton Multispecialist Hospital & Fertility Centre</strong> online booking system.</p>
        <p>Please follow up with the client to confirm their appointment.</p>
      </div>
    </div>
    `
  };

  await transporter.sendMail(mailOptions);
};

module.exports = sendEmail;
